version: '3.3'
services:
  spid-php-example-sp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8099:80'
    volumes:
      - type: bind
        source: ./sp_conf
        target: /app/sp_conf
    networks:
      - example1

  spid-php-example-idp:
    image: italia/spid-testenv2
    ports:
      - 8088:8088
    restart: always
    volumes:
      - type: bind
        source: ./idp_conf
        target: /app/conf
    networks:
      - example2

networks:
  example1:
    driver: bridge
  example2:
    driver: bridge
